packages/Sandblocks-Smalltalk/SBStBasicMethod.class.st, packages/Sandblocks-Smalltalk/SBStClass.class.st, packages/Sandblocks-Smalltalk/SBStMorphPalette.class.st
Show the Morph palette for methods located in the Morph class itself, too, as opposed to its super+classes only. Implement `#includesBehavior:` on `SBStClass` next to `#inheritsFrom:`, just in case. Minor refactoring.
=> Fix usage of `#inheritsFrom:`

packages/BaselineOfSandblocks/BaselineOfSandblocks.class.st
Spell out the repository path to make it compatible with other references, e.g., https://github.com/hpi-swa-lab/babylonian-programming-smalltalk/blob/e72647f9d397ab49dcd1f14e9814a513e5fa5ad3/packages/BaselineOfBabylonianProgramming.package/BaselineOfBabylonianProgramming.class/instance/baseline..st#L10. See also https://github.com/Metacello/metacello/pull/542.
=> Elaborate Ohm dependency in baseline

packages/Sandblocks-Core/SBBlock.class.st
* remove redundant string conversions (symbols are faster to compare)
* replace slow `#withoutDuplicates` by `#removeAllSuchThat:`
* use sort functions (not an optimization, just a refactoring :))
=> core: optimize suggestions, relates d47b6b6

packages/Sandblocks-Core/SBEditor.class.st
This will be [used](https://github.com/LinqLover/sonyx/blob/10b7cb4833f246534143c97e3162c0b8402ee44a/packages/Sonyx-UI.package/SonyxSandblocksContainer.class/instance/reloadArtefact.st) by Sonyx (sent from a subclass of `SBStContainer`).
=> core: add hook `#markSaved:` to `SBEditor`

packages/Sandblocks-Core/CodeHolder.extension.st, packages/Sandblocks-Core/Morph.extension.st, packages/Sandblocks-Core/SBOffscreenBlockIndicator.class.st, packages/Sandblocks-Core/SBOffscreenBlockIndicator.extension.st, packages/Sandblocks-Smalltalk/SBStContainer.class.st
most important: add `-override` suffix to extension methods that shadow existing methods from the base system, so that Monticello does not fall over them (e.g., if sandblocks should be ever unloaded, for instance during a squot operation)
=> :balloon: recategorize party :balloon:

packages/Sandblocks-Core/SBBlock.class.st
When the user clicks on an entered selector, they should still see all possible alternatives.
revises 640f139
=> core: fix `#suggestAlways` - show all suggestions always, even if we have started filtering

packages/BaselineOfSandblocks/BaselineOfSandblocks.class.st, packages/Sandblocks-Babylonian/SBTypeCollectSimulator.class.st, packages/Sandblocks-Core/SBReachabilitySimulatorTest.class.st, packages/Sandblocks-Representation/SBExtractFieldRepresentation.class.st, packages/Sandblocks-Smalltalk/SBExample.class.st, packages/Sandblocks-Smalltalk/SBStASTNode.class.st, packages/Sandblocks-Smalltalk/SBStReachabilitySimulator.class.st
This PR switches the existing simulation features of Sandblocks to [SimulationStudio](https://github.com/LinqLover/SimulationStudio). Concretely, this affects the following classes:
- `SBStSandboxSimulator`: Switched to SimulationStudio's `Sandbox`.
- `SBStReachabilitySimulator`: Switched from `SBStSimulator` to SimulationStudio's `SimulationContext`. Refined reachability detection to match every single PC.
- `SBTypeCollectSimulator:`: Switched from `InstructionClient` to SimulationStudio's `SimulationContext`.
- The baseline is updated accordingly.
Open todos:
---
<details>
<summary><b>Why SimulationStudio?</b> (may contain traces of self-advertising 👀)</summary>
- SimulationStudio reuses and makes extensible the original meta-interpreter of Squeak. As a consequence, no reinvention of …
=> Integrate SimulationStudio

packages/Sandblocks-Core/SBEditor.class.st, packages/Sandblocks-Core/SBShortcut.class.st
* refactoring, recategorizations
* changed semantics in SBShortcut: command, option, and ctrl are nullable; if they are not explicitly specified, these properties are not matched against events
* updated display string, removed `#cmdKeyString:` assume that Squeak users know the meaning of "Cmd" according to their preferences (instead of replicating all the complexity here again)
Seems to work for me on Windows with the preferences `EventSensor mapAltKeysToOptionKeys` and `EventSensor mapControlKeysToCommandKeys` being enabled. Now we need feedback from different platforms ... 😅
=> Fix keyboard shortcuts on Windows

packages/Sandblocks-Smalltalk/SBStASTNode.class.st
If the result of the speculative evaluation does not understand the non-inlined message `#class`, use the mirror primitive instead. See https://github.com/LinqLover/SimulationStudio/issues/33.
Happens for example if you try to guess the class of `ProtoObject new`.
=> Fix type-guessing for `ProtoObject`s

packages/Sandblocks-Core/CodeHolder.extension.st
=> Add preference getter for adding Sandblocks to `CodeHolder`s

packages/Sandblocks-Core/SBCommand.class.st, packages/Sandblocks-Smalltalk/SBStBinding.class.st, packages/Sandblocks-Smalltalk/SBStClass.class.st, packages/Sandblocks-Smalltalk/SBStClass.extension.st, packages/Sandblocks-Smalltalk/SBStCreateClassCommand.class.st, packages/Sandblocks-Smalltalk/SBStDeclareBehaviorVarCommand.class.st, packages/Sandblocks-Smalltalk/SBStDeclareClassVarCommand.class.st, packages/Sandblocks-Smalltalk/SBStDeclareInstVarCommand.class.st, packages/Sandblocks-Smalltalk/SBStNameBehavior.class.st
Only suggest fixes that follow the camelCase/PascalCase convention for Smalltalk identifiers. Extract `SBStDeclareBehaviorVarCommand` from `SBStDeclareInstVarCommand` and inherit from it in new `SBStDeclareClassVarCommand`. Add `SBStCreateClassCommand`. Partial recategorizations in related classes.
---
---
---
---
Undo works, too:
---
Also tested with `SBBrowserEditor`:
---
Remaining bugs (but rather not introduced by this patch):
- `SBGroup` is not automatically resized after inserting/removing a binding
Please do not hesitate to mention me in any follow-up commit that revises anything from this patch so that I can learn what to do better. :-)
=> st: add binding fix actions for creating classvar/new class

packages/Sandblocks-Morphs/SBButton.class.st
also fixes label computation if button has an icon only
=> morphs: implement "debug button action" feature on `SBButton`

packages/BaselineOfSandblocks/BaselineOfSandblocks.class.st
Otherwise, it would only appear in the menu after toggling on this pref one or more times.
Let's see whether it passes the CI! :-)
=> baseline: add block editor to 'what to show' menu on load

packages/Sandblocks-Tutorial/SBTutorialStep.class.st
The cursor must be position *behind* the last array item block, not inside the array item. Make sure that the previous item has not been overwritten.
=> tutorial: fix deletion step on insertion assertion

packages/Sandblocks-Babylonian/SBStTestCase.class.st, packages/Sandblocks-Core/SBASTNodeTest.class.st, packages/Sandblocks-Core/SBBlockTest.class.st, packages/Sandblocks-Core/SBClipboardTest.class.st, packages/Sandblocks-Core/SBInputDeleteTest.class.st, packages/Sandblocks-Core/SBMessagePartTest.class.st, packages/Sandblocks-Core/SBTest.class.st
This is necessary to complement SUnit-ct.130, which treats unhandled warnings as a failure of the test case. Note that there are still some other things to do at the moment:
* This particular exception is weird at all - a warning should not "do nothing" in its defaultAction, so maybe the superclass of this exception should be changed instead
* smalltalkCI has not yet been told about the new semantics of warnings in tests (I'm on it).
Given these points, I'm parking this patch here for now until the above points have been resolved ...
Depends on #92.
=> core: fix tests by catching unhandled UndeclaredVariableWarnings

packages/Sandblocks-Core/SBProjectionSuggestionItem.class.st, packages/Sandblocks-Smalltalk/SBColor.class.st, packages/Sandblocks-Smalltalk/SBExpandedMethod.class.st, packages/Sandblocks-Smalltalk/SBForm.class.st, packages/Sandblocks-Smalltalk/SBHalt.class.st, packages/Sandblocks-Smalltalk/SBIconPicker.class.st, packages/Sandblocks-Smalltalk/SBMemoize.class.st, packages/Sandblocks-Smalltalk/SBPoint.class.st, packages/Sandblocks-Smalltalk/SBStLanguageBox.class.st, packages/Sandblocks-Smalltalk/SBStNameBehavior.class.st, packages/Sandblocks-Smalltalk/SBStRegex.class.st, packages/Sandblocks-Smalltalk/SBStSubstitution.class.st, packages/Sandblocks-Smalltalk/SBStateMachineEditor.class.st, packages/Sandblocks-Smalltalk/SBToggledCode.class.st
A projection suggestion is an item in a suggestion menu like a normal suggestion but will insert a substitution when chosen for completion. With this patch, projections appear with a small preview in the suggestions menu that should make the choice more intuitive for users.
Besides, on the class-side protocol of st substitutions, `#instanceSuggestion` is extracted which answers a factory block for a new instance, making it easier for subclasses to provide their suggestions.
Suggestions are added to the substitutions memoize, point, language box, regex, and toggled code.
´
Open issues (ideally to be addressed while/before merging this):
Ideas for later:
- Union the knowledge bases from `instanceSuggestion`s and palettes
- Provide these suggestions without using the explicit protocol from …
=> core/st: add UI for projection suggestions

packages/Sandblocks-Smalltalk/SBStMessageSend.class.st, packages/Sandblocks-Smalltalk/SBStNewMessageSend.class.st, packages/Sandblocks-Smalltalk/SBStSignature.class.st
st: honor guessed class for mining of possible argument names 
Testing:
Morph new click: ...
ListStub new click: ...
The argument name should be chosen from the right implementation preferably. The previous detection mechanism proposed to wrong name.
However, this solution is still not perfect IMHO. Depending on the situation, less confusion might be caused by eliminating the second pass via #systemNavigation entirely, i.e., providing no custom argument names at all if type guessing failed. Wdyt?
Also, what would be a proper place to eliminate the duplication between SbStNewMessageSend and SBStSignature?
=> Type-sensitive suggestion arg names

packages/Sandblocks-Core/SBBlock.class.st, packages/Sandblocks-Core/SBEditor.class.st
As discussed. This prevents the suggestions menu from being clipped within the editor and at the same time makes sure it always appears at the right time when an artefact or the editor is moved.
See also:  https://github.com/tom95/sandblocks/commit/66e28689c4992a4707c78b4fbbab7b4c0a7ba573.
=> core: revise opening of suggestions menu, always open in world + reposition

packages/Sandblocks-Core/SBBlock.class.st, packages/Sandblocks-Core/SBSuggestionItem.class.st, packages/Sandblocks-Core/SBSuggestionMenu.class.st
In particular, add an early exit to `#activeItem:` to make `SBSuggestionItem >> #active:` a more meaningful hook. (Sonyx makes use of this hook in a subclass.)
=> core: mv `SBSuggestionMenu>>#active{Suggestion,Item}`

packages/Sandblocks-Debugger/.squot-contents, packages/Sandblocks-Debugger/SBSmallError.class.st
Previously, invocating the action `#debug` on an `SBExample` failed because `SBSmallError` did not understand `#focus`.
=> debugger: fix debugging of examples

packages/Sandblocks-Smalltalk/.squot-contents, packages/Sandblocks-Smalltalk/SBStBasicMethod.class.st, packages/Sandblocks-Smalltalk/SBToggledCode.class.st
Since Morphic-ct.1906 (Trunk), `#setProperty:[...]` and `#removeProperty:` answer the property value instead of the receiver. In `SBToggledCode`, this led to an actual DNU. I quickly skimmed all other senders of both selectors and Sandblocks and did not identify any third violation.
=> st: fix use of Morph property protocol

packages/Sandblocks-Babylonian/SBStTestCase.class.st, packages/Sandblocks-Babylonian/TestResult.extension.st, packages/Sandblocks-Core/SBBrowserEditor.class.st, packages/Sandblocks-Core/SBClipboardTest.class.st, packages/Sandblocks-Core/SBEditor.class.st
This change is visible when you run an SBStTestCase from a browser editor. In the past, the test result icon in the containing browser's message list would not have been updated (as compared to running the same test via the message list menu > "run test") - now this works. See also: `CodeHolder>>#testRunSuite:`.
⚠️ Please report back whether you like this display. An alternative would be compound icons (such as <kbd>✔️⚠️</kbd> or <kbd>❌✔️</kbd>) with an explaining tool tip. I'm not sure what gives the best UX.
Nit.
=> SBStTestCase: Update history and honor expected failures

packages/Sandblocks-Core/SBColorPolicy.class.st, packages/Sandblocks-Smalltalk/SBStBasicMethod.class.st, packages/Sandblocks-Smalltalk/SBStDeclarationForBehaviorVariable.class.st, packages/Sandblocks-Smalltalk/SBStDeclarationForClassVariable.class.st, packages/Sandblocks-Smalltalk/SBStDeclarationForInstanceVariable.class.st, packages/Sandblocks-Smalltalk/SBStName.class.st, packages/Sandblocks-Smalltalk/SBStNameBehavior.class.st
- `SBStNameBehavior>>suggestions`: Do not distinguish between syntactical casing (lowercase/uppercase) of the suggestions but rather between their origin (local/global), since class vars are actually scoped locally
- new sibling class `SBStDeclarationForClassVariable` of `SBStDeclarationForInstanceVariable` with common features extracted into new superclass `SBStDeclarationForBehaviorVariable`
- improved type guessing for class variables and instance variables of singleton (class objects)
=> st: add suggestions for class variables

packages/Sandblocks-Core/SBNamedBlock.class.st, packages/Sandblocks-Core/SBTextBubble.class.st, packages/Sandblocks-Core/SBUnwrapConsecutiveCommand.class.st, packages/Sandblocks-Core/SBVimInputMapping.class.st, packages/Sandblocks-Morphs/SBButton.class.st, packages/Sandblocks-Morphs/SBEditableButton.class.st, packages/Sandblocks-Morphs/SBOwnTextMorph.class.st, packages/Sandblocks-Morphs/SBStringMorph.class.st, packages/Sandblocks-Morphs/SBTabView.class.st, packages/Sandblocks-Smalltalk/SBStASTNode.class.st, packages/Sandblocks-Smalltalk/SBStGrammarHandler.class.st, packages/Sandblocks-Smalltalk/SBVariant.class.st
`SBVariants` are an enhanced option to `SBToggledCode` which work with any kind of sandblock. With an introduced `TabView`, similiar to browsers, users can choose one of multiple blocks which is displayed and executed. The tab has navigation, add and remove shortcuts. Furthermore, the actions are reversable commands. The tabs themselves are `SBNamedBlocks`, a new helper struct contained of a block and a name.
=> Introduce Variants

packages/Sandblocks-Babylonian/SBExampleValueDisplay.class.st, packages/Sandblocks-Babylonian/SBExampleWatch.class.st, packages/Sandblocks-Babylonian/SBExampleWatch.extension.st, packages/Sandblocks-Babylonian/SBInactiveExampleWatch.class.st, packages/Sandblocks-Babylonian/SBInactiveExampleWatch.extension.st, packages/Sandblocks-Babylonian/SBResultsView.class.st, packages/Sandblocks-Babylonian/SBVariantsView.class.st, packages/Sandblocks-Babylonian/SBWatchValueBlock.class.st, packages/Sandblocks-Core/SBLabel.class.st, packages/Sandblocks-Core/SBTabView.class.st, packages/Sandblocks-Core/SBTextBubble.class.st, packages/Sandblocks-Morphs/SBEditableButton.class.st, packages/Sandblocks-Smalltalk/SBStASTNode.class.st, packages/Sandblocks-Smalltalk/SBStGrammarHandler.class.st, packages/Sandblocks-Smalltalk/SBStMethod.class.st, packages/Sandblocks-Smalltalk/SBVariant.class.st, packages/Sandblocks-Utils/SBPermutation.class.st, packages/Sandblocks-Watch/SBWatchView.class.st
* Inactive Watches' watched expressions not changeable
* SBVariants in SBWatches & Vice Versa
* Smaller SBVariants label
* Exploriants handles no variants
* Resolves Exploriants bindings
* Double click on watches & variants
* Shift + " now creates optional variant instead of toggled code
* warpInVariant automatically creates second alternative tab
* different displays in sbexamplewatches now use scrollpane
=> Several Exploriants Quality Of Lives 

packages/Sandblocks-Babylonian/SBExampleValueDisplay.class.st, packages/Sandblocks-Babylonian/SBExampleWatch.class.st, packages/Sandblocks-Babylonian/SBExampleWatch.extension.st, packages/Sandblocks-Babylonian/SBInactiveExampleWatch.class.st, packages/Sandblocks-Babylonian/SBInactiveExampleWatch.extension.st, packages/Sandblocks-Babylonian/SBResultsView.class.st, packages/Sandblocks-Babylonian/SBVariantsView.class.st, packages/Sandblocks-Babylonian/SBWatchValueBlock.class.st, packages/Sandblocks-Core/Collection.extension.st, packages/Sandblocks-Core/SBLabel.class.st, packages/Sandblocks-Core/SBTabView.class.st, packages/Sandblocks-Core/SBTextBubble.class.st, packages/Sandblocks-Morphs/SBEditableButton.class.st, packages/Sandblocks-Morphs/SBOwnTextMorph.class.st, packages/Sandblocks-Smalltalk/SBStASTNode.class.st, packages/Sandblocks-Smalltalk/SBStGrammarHandler.class.st, packages/Sandblocks-Smalltalk/SBStMethod.class.st, packages/Sandblocks-Smalltalk/SBVariant.class.st, packages/Sandblocks-Utils/SBPermutation.class.st, packages/Sandblocks-Watch/SBAxisNotation.class.st, packages/Sandblocks-Watch/SBBarChart.class.st, packages/Sandblocks-Watch/SBLineChart.class.st, packages/Sandblocks-Watch/SBRectangleChart.class.st, packages/Sandblocks-Watch/SBScale.class.st, packages/Sandblocks-Watch/SBVisualization.class.st, packages/Sandblocks-Watch/SBWatchView.class.st
For quick overview of a collection of either numbers or points, users can now click on the visualization button next to an example's label in a watch. Currently implemented are line charts, bar charts, and rectangle charts, which all implement the abstract `SBVisualization` class. They replace the existing `SBGraphPlot` class which is now obsolete and deleted. 
For scaling behavior similiar to d3, a `SBScale` has been added. `SBAxisNotation` is responsible for displaying ticks. 
This MR is dependent on #124 which should be merged first.
=> Graphs for Example Watches

packages/Sandblocks-Babylonian/SBExampleValueDisplay.class.st, packages/Sandblocks-Babylonian/SBExampleWatch.class.st, packages/Sandblocks-Babylonian/SBExploriants.class.st, packages/Sandblocks-Babylonian/SBInactiveExampleWatch.class.st, packages/Sandblocks-Babylonian/SBInactiveExampleWatch.extension.st, packages/Sandblocks-Smalltalk/SBVariant.class.st, packages/Sandblocks-Watch/SBMorphResizer.class.st, packages/Sandblocks-Watch/SBWatchView.class.st
Previously, watched objects were static. The variants were only selected differently once when creating Exploriants. However, for methods such as step, this results in the same behavior for every permutation. This MR saves permutations in Exploriants and asks them when a variant is dissolved
=> Adds support for variants in dynamic ui methods

packages/Sandblocks-Babylonian/SBExampleValueDisplay.class.st, packages/Sandblocks-Babylonian/SBExampleWatch.class.st, packages/Sandblocks-Watch/SBBarChart.class.st, packages/Sandblocks-Watch/SBLineChart.class.st, packages/Sandblocks-Watch/SBRectangleChart.class.st, packages/Sandblocks-Watch/SBVisualization.class.st, packages/Sandblocks-Watch/SBWatchView.class.st
Instead of creating watch values on a resize, `SBWatchView` is responsible for resizing now. That way, different displays can be resized too. 
Refactors `SBVisualization` to be flexible in size
=> Consistent Resizing in Watches

packages/Sandblocks-Babylonian/SBExploriants.class.st, packages/Sandblocks-Core/SBTabView.class.st, packages/Sandblocks-Smalltalk/SBStMessageSend.class.st, packages/Sandblocks-Smalltalk/SBVariant.class.st
Adds a diffing button to tab views. On click, they reveal basic text diffs from the system's `TextDiffBuilder` from one tab to the others. Makes comparisons quicker.
Also fixes a fault in which only the last statement of an alternative was looked at in saving, replacing, etc.. The failure occured as soon as multiple lines are added.
=> Basic diffing between alternatives in `SBTabView`s

packages/Sandblocks-Babylonian/SBDiffTabView.class.st, packages/Sandblocks-Babylonian/SBExampleGridsView.class.st, packages/Sandblocks-Babylonian/SBExploriants.class.st, packages/Sandblocks-Babylonian/SBExploriantsView.class.st, packages/Sandblocks-Babylonian/SBGridResultsView.class.st, packages/Sandblocks-Babylonian/SBInactiveExampleWatch.class.st, packages/Sandblocks-Babylonian/SBInactiveExampleWatch.extension.st, packages/Sandblocks-Babylonian/SBInputBroadcaster.class.st, packages/Sandblocks-Babylonian/SBLiveView.class.st, packages/Sandblocks-Babylonian/SBPermutationGridsView.class.st, packages/Sandblocks-Babylonian/SBResultsView.class.st, packages/Sandblocks-Core/SBTabView.class.st
With a given setup, the newly added Live View builds several Morphs which each behave like a universe of the multiverse. This allows for simultaneous testing of interactive classes like games and see changes right next to one another.
https://github.com/hpi-swa/sandblocks/assets/33000454/ec944e65-c822-40c0-afd5-f65f26e3dc74
With the Live View come two new classes:
1) `SBInputBroadcaster` a special block which sends its events to all its registered listeners. As elements like Buttons only work by handling events with the cursor, a temporary `HandMorph` handles mouse events. Drag events are not supported as of now. 
2) `SBLiveView` which offers a block for setup and generates a grid with a broadcaster and listeners. To resolve bindings and have consistent sizing, a few adjustments to …
=> Live View of Permutations

packages/Sandblocks-Core/SBBlock.class.st, packages/Sandblocks-Smalltalk/SBVariant.class.st, packages/Sandblocks-Utils/SBPermutation.class.st
Given a nested variant like this
The permutations red>original and red>alternative will never occur, as the variant is nested inside green. This MR changes the simple permutation calculation of crossing everything with each other to a dfs crossing of top level variants.
=> Ignore un-nested permutations which are not possible

packages/Sandblocks-Babylonian/Morph.extension.st, packages/Sandblocks-Babylonian/SBCluster.class.st, packages/Sandblocks-Babylonian/SBEditor.extension.st, packages/Sandblocks-Babylonian/SBExample.class.st, packages/Sandblocks-Babylonian/SBExampleCluster.class.st, packages/Sandblocks-Babylonian/SBExampleWatch.class.st, packages/Sandblocks-Babylonian/SBExploriants.class.st, packages/Sandblocks-Babylonian/SBExploriantsView.class.st, packages/Sandblocks-Babylonian/SBInactiveExampleWatch.class.st, packages/Sandblocks-Babylonian/SBLiveView.class.st, packages/Sandblocks-Babylonian/SBMultiverse.class.st, packages/Sandblocks-Babylonian/SBPermutationGridsView.class.st, packages/Sandblocks-Babylonian/SBPermutationLabel.class.st, packages/Sandblocks-Babylonian/SBPermutationLabel.extension.st, packages/Sandblocks-Babylonian/SBPlainResultsView.class.st, packages/Sandblocks-Babylonian/SBResultsView.class.st, packages/Sandblocks-Babylonian/SBStGrammarHandler.extension.st, packages/Sandblocks-Core/SBBlock.class.st, packages/Sandblocks-Core/SBGrammarHandler.class.st, packages/Sandblocks-Core/SBLabel.class.st, packages/Sandblocks-Core/SBTabView.class.st, packages/Sandblocks-Core/SBUnknown.class.st, packages/Sandblocks-Core/SBVimInputMapping.class.st, packages/Sandblocks-Morphs/SBButton.class.st, packages/Sandblocks-Smalltalk/SBStGrammarHandler.class.st, packages/Sandblocks-Smalltalk/SBVariant.class.st, packages/Sandblocks-Utils/SBPermutation.class.st, packages/Sandblocks-Watch/SBExampleWatchView.class.st, packages/Sandblocks-Watch/SBWatchView.class.st
Ignore branch name, fixed now ;)
Part 2 of #138 with following features:
- Variants can be turned inactive through the context menu and will be ignored when generating the multiverse
- Builds upon the concept of naming variants by creating "commented sections" on default when commenting. This is none other than a variant with one alternative. That way, variant usage is encouraged and cleanup of comments easier as they can be resolved by resolving the variant or using exploriant's cleanup. Double clicking the name will result in the block resolving to a SBLabel, to still enable conventional comments for e.g. documentation. 
- Exploriants now displays watches even though they are not open in the editor
- Some more automatic method saves when adding live elements, which is done equally in …
=> Usage (+technical) Improvements Part 2

packages/Sandblocks-Babylonian/SBCluster.class.st, packages/Sandblocks-Babylonian/SBDiffTabView.class.st, packages/Sandblocks-Babylonian/SBExampleCluster.class.st, packages/Sandblocks-Babylonian/SBExampleGridsView.class.st, packages/Sandblocks-Babylonian/SBExampleValueDisplay.class.st, packages/Sandblocks-Babylonian/SBExampleWatch.class.st, packages/Sandblocks-Babylonian/SBExploriantsView.class.st, packages/Sandblocks-Babylonian/SBGrid.class.st, packages/Sandblocks-Babylonian/SBGridResultsView.class.st, packages/Sandblocks-Babylonian/SBHistoryView.class.st, packages/Sandblocks-Babylonian/SBLiveView.class.st, packages/Sandblocks-Babylonian/SBMultiverse.class.st, packages/Sandblocks-Babylonian/SBPermutationGridsView.class.st, packages/Sandblocks-Babylonian/SBPlainResultsView.class.st, packages/Sandblocks-Babylonian/SBSwitchableResultsView.class.st, packages/Sandblocks-Babylonian/SBTrace.class.st, packages/Sandblocks-Babylonian/SBVariantsView.class.st, packages/Sandblocks-Core/SBTabView.class.st, packages/Sandblocks-Watch/SBBarChart.class.st, packages/Sandblocks-Watch/SBExampleWatchView.class.st, packages/Sandblocks-Watch/SBLineChart.class.st, packages/Sandblocks-Watch/SBRectangleChart.class.st, packages/Sandblocks-Watch/SBVisualization.class.st, packages/Sandblocks-Watch/SBWatchView.class.st
Adds a history tab to exploriants which takes pictures of the views and gathers them in a tab view for a moment of time when a multiverse is generated
For a more compact view, changes from a square-grid-layout to filling in as much space horizontally as the open editor allows, which is likely to be similiar to the users' displays. Some margins and insets have been reduced too. 
Another big change is the visualization of watch value collections in exploriants. Normally, even with a line chart as a display chosen, exploriants would cramp the serialized values in a grid, which can get ugly for smaller sizes.
Now, the displays chosen are taken over in the grid view, still presenting a challenge for smaller sizes, but good visual cues when enlarged and compared to just text
=> History Tab in Exploriants, Tab Renaming, Space compression

packages/Sandblocks-Babylonian/Morph.extension.st, packages/Sandblocks-Babylonian/SBCorrelationView.class.st, packages/Sandblocks-Babylonian/SBExampleWatch.class.st, packages/Sandblocks-Babylonian/SBExploriants.class.st, packages/Sandblocks-Babylonian/SBExploriantsView.class.st, packages/Sandblocks-Babylonian/SBGridResultsView.class.st, packages/Sandblocks-Babylonian/SBMultiverse.class.st, packages/Sandblocks-Babylonian/SBPlainResultsView.class.st, packages/Sandblocks-Babylonian/SBSwitchableResultsView.class.st, packages/Sandblocks-Babylonian/SBTrace.class.st, packages/Sandblocks-Babylonian/SBVariantsView.class.st, packages/Sandblocks-Core/Collection.extension.st, packages/Sandblocks-Core/SBTabView.class.st, packages/Sandblocks-Smalltalk/SBStGrammarHandler.class.st, packages/Sandblocks-Smalltalk/SBVariant.class.st, packages/Sandblocks-Smalltalk/SBVariantProxy.class.st, packages/Sandblocks-Utils/SBPermutation.class.st, packages/Sandblocks-Watch/SBLineChart.class.st, packages/Sandblocks-Watch/SBWatchView.class.st
-few size fixes (2 -> 2 sbScaled)
-rename watch -> probe
-delete ignoreReports in probes
-make permutation generation more readable
-bug fixing for applying oudated permutations
-remote variation point changing / bugfixing
=> SBExploriants Refactorings
